#Problem 45
#06 June 2003
#Triangle, pentagonal, and hexagonal numbers are generated by the following
# formulae:    Triangle   T n = n ( n +1)/2   1, 3, 6, 10, 15, ...    Pentagona
#l   P n = n (3 n 1)/2   1, 5, 12, 22, 35, ...    Hexagonal   H n = n (2 n 1)  
# 1, 6, 15, 28, 45, ...    It can be verified that T 285 = P 165 = H 143 =
# 40755.  Find the next triangle number that is also pentagonal and hexagonal.
#
#----------


tph = False
t = 285
p = 165
h = 143
num = 40755

def hex_calc(hc):
	return hc * (2 * hc - 1)
	
def pent_calc(pc):
	return (pc * (3 * pc - 1)) / 2
	
def tri_calc(tc):
	return (tc * (tc + 1)) / 2

while tph == False:
	h += 1
	while pent_calc(p) < hex_calc(h):
		p += 1
	while tri_calc(t) < hex_calc(h):
		t += 1
	if tri_calc(t) == pent_calc(p) == hex_calc(h):
		tph = True
	print hex_calc(h)
	print pent_calc(p)
	print tri_calc(t)
		
print tri_calc(t)