#Unsolved
#
#Problem 12
#08 March 2002
#The sequence of triangle numbers is generated by adding the natural numbers. S
#o the 7 th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
# ten terms would be:  1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...  Let us list th
#e factors of the first seven triangle numbers:  1 : 1  3 : 1,3  6 : 1,2,3,6  1
#0 : 1,2,5,10  15 : 1,3,5,15  21 : 1,3,7,21  28 : 1,2,4,7,14,28  We can see tha
#t 28 is the first triangle number to have over five divisors.  What is the
# value of the first triangle number to have over five hundred divisors?
#
#----------


import time, math
s = time.time()
divisors = 0
xth_triangle_number = 1
triangle_number = 0

while divisors <= 500:

	triangle_number += xth_triangle_number
	divisors = 0
	print triangle_number
	n = xth_triangle_number
	if triangle_number % 2 == 0:
		for b in range(1, (triangle_number/2)):
			if triangle_number % b == 0:
				divisors += 1
	else:
		for b in range(1, int(triangle_number/2) + 1):
			if triangle_number % b == 0:
				divisors += 1
	divisors += 1
	print "Divisors: ", divisors
	xth_triangle_number += 1
	
print "Triangle number = ", triangle_number
print "Time: ", time.time() - s