#Unsolved
#
#Problem 44
#23 May 2003
#Pentagonal numbers are generated by the formula, P n = n (3 n 1)/2. The first
# ten pentagonal numbers are:  1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...  It
# can be seen that P 4 + P 7 = 22 + 70 = 92 = P 8 . However, their difference,
# 70 22 = 48, is not pentagonal.  Find the pair of pentagonal numbers, P j and 
#P k , for which their sum and difference is pentagonal and D = |P k  P j | is
# minimised; what is the value of D?
#
#----------



pent_list = []

for a in range(1, 5000):
	pent_a = a*(3*a - 1)/2
	print pent_a
	pent_list.append(pent_a)
	
pent_d_list = []
	
for b in range(len(pent_list)):
	print b
	for c in range(b, len(pent_list)):
		pent_sum = pent_list[b] + pent_list[c]
		pent_diff = pent_list[c] - pent_list[b]
		if (pent_sum in pent_list) and (pent_diff in pent_list):
			pent_d_list.append(pent_diff)

print sorted(pent_d_list)