#Problem 2
#19 October 2001
#Each new term in the Fibonacci sequence is generated by adding the previous tw
#o terms. By starting with 1 and 2, the first 10 terms will be:  1, 2, 3, 5, 8,
# 13, 21, 34, 55, 89, ...  By considering the terms in the Fibonacci sequence
# whose values do not exceed four million, find the sum of the even-valued
# terms.
#
#----------

previous = 1
current = 1
fib = 1
running_count = 0
while fib <= 4000000:
	fib = current + previous
	print fib
	previous = current
	current = fib
	if fib % 2 == 0:
		running_count = running_count + fib
print "running count = ", running_count